name: Android Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: '8.9'
          gradle-home-cache-cleanup: true

      - name: Clear previous Gradle cache (force Gradle 8.9)
        run: |
          rm -rf ~/.gradle/caches
          rm -rf ~/.gradle/wrapper
          rm -rf ~/.gradle/daemon
          rm -rf ~/.gradle/gradle.properties
          echo "org.gradle.daemon=false" >> gradle.properties
          echo "Gradle cache cleaned."
  
      
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      
      - name: Run unit tests
        run: ./gradlew testDebugUnitTest
      
      - name: Generate test coverage report
        run: ./gradlew testDebugUnitTestCoverage
      
      - name: Upload test reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-reports
          path: app/build/reports/tests/
      
      - name: Upload coverage reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: coverage-reports
          path: app/build/reports/coverage/
      